### PR TITLE
Add D Syntax

### PR DESCRIPTION
**Pull request by RealDoigt**
This PR adds support for the D programming language with a d.nanorc file.

### CODE REVIEW

**Comment by RealDoigt** [comment]
Will this pr at least be acknowledged?

**Comment by RealDoigt** [comment]
@madnight is this mirror readonly, I saw other prs though? Why is this simple pr not getting any attention, whether it is to reject it or accept it, a single language file should be easy and fast to deal with.

**Comment by madnight** [comment]
@RealDoigt Hi, this repository is a read-only mirror. For pull requests, please reach out to the upstream nano developers. I don't have any influence over adding new features to the upstream.

**Comment by RealDoigt** [comment]
thank you for clarifying that this is readonly. have a good day

**Pull request closed without merging**
